### ISSUE TITLE
個人用 MODPACK を使用すると GTE がクラッシュする

### ISSUE THREAD

**Issue by Someonerandomidk** [GTModpackTeam/GTExpert-Core#202]
基本的に、私は個人的な Modpack を作成しているときにこの Mod を偶然発見し、さらにグレッグのために追加することにしました。
問題は、modpack を起動すると、何をしても、ステージ 4 で常に次のエラーが発生することです。
ava.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at gtexpert.loaders.recipe.ingredients.AERecipeLoader.materials(AERecipeLoader.java:66)
    at gtexpert.loaders.recipe.ingredients.AERecipeLoader.init(AERecipeLoader.java:42)
    at gtexpert.loaders.recipe.GTERecipeManager.loadLowest(GTERecipeManager.java:36)
    at gtexpert.common.CommonProxy.registerRecipesLowest(CommonProxy.java:115)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_323_CommonProxy_registerRecipesLowest_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:6601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
私は、GregTech CEu バージョン 2.8.5 および AE2 Unofficial Extended Life とそのアドオンのほとんどを備えた最新バージョン (1.5.13) を使用しています。

完全なログはこちら:
[crash-2023-12-21_15.22.29-client.txt](https://github.com/GTModpackTeam/GTExpert-Core/files/13746057/crash-2023-12-21_15.22.29-client.txt)

**Comment by Someonerandomidk** [comment]
ちなみに、これは私のmodlistです:
(by the way this is my modlist:)
[modlist.txt](https://github.com/GTModpackTeam/GTExpert-Core/files/13747019/modlist.txt)
